import {Converter} from "../core/utils/RTConverter";


export const {
    A,
    Abbr,
    Acronym,
    Address,
    Applet,
    Area,
    Article,
    Aside,
    Audio,
    B,
    Base,
    Basefont,
    Bb,
    Bdo,
    Big,
    Blockquote,
    Body,
    Br,
    Button,
    Canvas,
    Caption,
    Center,
    Cite,
    Code,
    Col,
    Colgroup,
    Command,
    Datagrid,
    Datalist,
    Dd,
    Del,
    Details,
    Dfn,
    Dialog,
    Dir,
    Div,
    Dl,
    Dt,
    Em,
    Embed,
    Eventsource,
    Fieldset,
    Figcaption,
    Figure,
    Font,
    Footer,
    Form,
    Frame,
    Frameset,
    H1, 
    H2, 
    H3, 
    H4, 
    H5, 
    H6,
    Head,
    Header,
    Hgroup,
    Hr,
    Html,
    I,
    Iframe,
    Img,
    Input,
    Ins,
    Isindex,
    Kbd,
    Keygen,
    Label,
    Legend,
    Li,
    Link,
    Map,
    Mark,
    Menu,
    Meta,
    Meter,
    Nav,
    Noframes,
    Noscript,
    Object,
    Ol,
    Optgroup,
    Option,
    Output,
    P,
    Param,
    Pre,
    Progress,
    Q,
    Rp,
    Rt,
    Ruby,
    S,
    Samp,
    Script,
    Section,
    Select,
    Small,
    Source,
    Span,
    Strike,
    Strong,
    Style,
    Sub,
    Sup,
    Table,
    Tbody,
    Td,
    Textarea,
    Tfoot,
    Th,
    Thead,
    Time,
    Title,
    Tr,
    Track,
    Tt,
    U,
    Ul,
    Var,
    Video,
    Wbr
} = Converter({
    A: "a",
    Abbr: "abbr",
    Acronym: "acronym",
    Address: "address",
    Applet: "applet",
    Area: "area",
    Article: "article",
    Aside: "aside",
    Audio: "audio",
    B: "b",
    Base: "base",
    Basefont: "basefont",
    Bb: "bb",
    Bdo: "bdo",
    Big: "big",
    Blockquote: "blockquote",
    Body: "body",
    Br: "br",
    Button: "button",
    Canvas: "canvas",
    Caption: "caption",
    Center: "center",
    Cite: "cite",
    Code: "code",
    Col: "col",
    Colgroup: "colgroup",
    Command: "command",
    Datagrid: "datagrid",
    Datalist: "datalist",
    Dd: "dd",
    Del: "del",
    Details: "details",
    Dfn: "dfn",
    Dialog: "dialog",
    Dir: "dir",
    Div: "div",
    Dl: "dl",
    Dt: "dt",
    Em: "em",
    Embed: "embed",
    Eventsource: "eventsource",
    Fieldset: "fieldset",
    Figcaption: "figcaption",
    Figure: "figure",
    Font: "font",
    Footer: "footer",
    Form: "form",
    Frame: "frame",
    Frameset: "frameset",
    H1: "h1",
    H2: "h2",
    H3: "h3",
    H4: "h4",
    H5: "h5",
    H6: "h6",
    Head: "head",
    Header: "header",
    Hgroup: "hgroup",
    Hr: "hr",
    Html: "html",
    I: "i",
    Iframe: "iframe",
    Img: "img",
    Input: "input",
    Ins: "ins",
    Isindex: "isindex",
    Kbd: "kbd",
    Keygen: "keygen",
    Label: "label",
    Legend: "legend",
    Li: "li",
    Link: "link",
    Map: "map",
    Mark: "mark",
    Menu: "menu",
    Meta: "meta",
    Meter: "meter",
    Nav: "nav",
    Noframes: "noframes",
    Noscript: "noscript",
    Object: "object",
    Ol: "ol",
    Optgroup: "optgroup",
    Option: "option",
    Output: "output",
    P: "p",
    Param: "param",
    Pre: "pre",
    Progress: "progress",
    Q: "q",
    Rp: "rp",
    Rt: "rt",
    Ruby: "ruby",
    S: "s",
    Samp: "samp",
    Script: "script",
    Section: "section",
    Select: "select",
    Small: "small",
    Source: "source",
    Span: "span",
    Strike: "strike",
    Strong: "strong",
    Style: "style",
    Sub: "sub",
    Sup: "sup",
    Table: "table",
    Tbody: "tbody",
    Td: "td",
    Textarea: "textarea",
    Tfoot: "tfoot",
    Th: "th",
    Thead: "thead",
    Time: "time",
    Title: "title",
    Tr: "tr",
    Track: "track",
    Tt: "tt",
    U: "u",
    Ul: "ul",
    Var: "var",
    Video: "video",
    Wbr: "wbr"
})
  